version: 2.1
orbs:
  # Orbs contain basic recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  build:
    docker:
      # The base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      # Install node and checkout code
      - node/install:
          node-version: '14.15'
      - checkout
      # Use root level package.json to install dependencies in the frontend app
      - run:
          name: Install Front-End Dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run frontend:install
      # Install dependencies in the backend API          
      - run:
          name: Install API Dependencies
          command: |
            npm run api:install
      # Lint the frontend
      - run:
          name: Front-End Lint
          command: |
            npm run frontend:lint
      # Build the frontend app
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      # Build the backend API      
      - run:
          name: API Build
          command: |
            npm run api:build
  deploy:
    docker:
      - image: "cimg/base:stable"
    environment:
      aws-access-key-id: $AWS_ACCESS_KEY_ID
      aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
      aws-region: $AWS_REGION
    steps:
      - eb/setup
      - aws-cli/setup
      - run:
          name: Deploy Backend
          command: npm run api:deploy

workflows:
  udagram:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
